import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillInstagram} from 'react-icons/ai'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Alexander Zhao Portfolio</title>
        <meta name="description" content="Generated by cre"></meta>
        <link rel="icon" href="/favion.ico" />
      </Head>
      <main className='bg-white px-10'>
        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-2xl text-cyan-500 font-burton'>Developed by Alex</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill className='cursor-pointer text-2xl text-black' /></li>
              <li><a className = 'bg-gradient-to-r from-cyan-500 to-teal-500 px-4 py-2 rounded-md ml-8'href="#">Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-5'>
            <h2 className='text-purple-600 text-5xl py-2 '>Alexander Zhao</h2>
            <h3 className='text-black '>Software and Machine Learning Developer | Computer Science Student</h3>
            <p className = 'text-black'>I am a self-motivated second-year undergraduate student at Queen's University studying computer science with a specialization in Software Design. I am passionate about programming and am always eager to learn and try out new technologies. I have experience in developing software applications and am also interested in machine learning and data analysis.</p>
          </div>
          <div className='text-black'>
            <AiFillTwitterCircle/>
            <AiFillInstagram/>
            <AiFillLinkedin/>
          </div>
        </section>
      </main>

    </div>
  );
}
