"use client";
import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillInstagram} from 'react-icons/ai'
import Image from "next/image";
import intro from "../public/intro.png";
import { useState } from 'react';
import design from "../public/design.png"


export default function Home() {
  const[darkMode, setDarkMode] = useState(false); 
  return (
    <div className={darkMode ? "dark": ""}>
      <Head>
        <title>Alexander Zhao Portfolio</title>
        <meta name="description" content="Generated by cre"></meta>
        <link rel="icon" href="/favion.ico" />
      </Head>
      <main className='bg-white px-10 dark:bg-gray-800'>
        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-2xl text-cyan-500 font-burton'>Developed by Alex</h1>
            <ul className='flex items-center'>
              <li><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl text-black' /></li>
              <li><a className = 'bg-gradient-to-r from-cyan-500 to-teal-500 px-4 py-2 rounded-md ml-8' href="" target='_blank' rel="noopener noreferrer" >Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-5'>
            <h2 className='text-purple-600 text-5xl py-2 font-medium '>Alexander Zhao</h2>
            <h3 className='text-black text-2xl py-2 '>Fullstack and Machine Learning Developer | Computer Science Student</h3>
            <p className = 'text-gray-800 text-md py-5 leading-8 '>I am a self-motivated second-year undergraduate student at Queen's University studying computer science with a specialization in Software Design. I am passionate about programming and am always eager to learn and try out new technologies. I have experience in developing software applications and am also interested in machine learning and data analysis.</p>
          </div>
          <div className='text-gray-600 text-3xl flex justify-center gap-10'>
            <AiFillTwitterCircle/>
            <AiFillInstagram/>
            <AiFillLinkedin/>
          </div>
          <div className='mx-auto my-10 bg-gradient-to-b from-gray-600 to-orange-100 rounded-full w-72 h-50 overflow-hidden '>
          <Image
           src= {intro} 
           alt='Image'
           className='mr-8'/>
           </div>
        </section>
        <section className="min-h-screen text-center">
          <div className='text-black '>
            <h3 className='-mt-24 text-3xl py-1 text-center'>My Journey as a Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800'> A <span className='text-teal-500'> blurb</span> this is how u highlight text btw about experience, and projects , and school.</p>
          </div>
          <div>
            <div>
              <Image src = {design} width={100} height={100}/>
            </div>
          </div>
        </section>
      </main>

    </div>
  );
}
